name: Run autotests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: Select tests to run
        required: true
        type: choice
        default: all
        options:
          - all
          - smoke
          - regression

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest selenium allure-pytest webdriver-manager

      - name: Show installed packages
        run: pip list

      - name: Run tests
        run: |
          pytest -v
